version: '3'
services:
    project:
        image: davisouza/rust:dev
        build:
          context: .
          dockerfile: Dockerfile
        container_name: project
        working_dir: /project
        command: cargo run
        volumes:
            - ./:/project/:consistent
        ports:
            - 5001:5000
networks:
    default:
        external:
            name: ds_network
