version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  app:
    # image: rust:1.54.0-slim-bullseye
    image: davisouza/rust:dev
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: kafka
    working_dir: /kafka/
    ports:
      - 8000:8000
    volumes:
      - ./:/kafka/:consistent

# apt install librdkafka-dev build-essential